baseURL = "http://lab0x0.com/"
title = "零空间 / LAB ZERO"
theme = "tilda"
description = "创客空间 真的 / The only one a real true makerspace in Shenzhen"

[blackfriday]
  extensions = ["hardLineBreak"]

[params]
    subtitle = "创客空间 真的 / The only one a real true makerspace in Shenzhen"
    fbAppID = "257953674358265"
    OgImage = "tild3431-6336-4565-b665-376335346639__shutterstock_256309363_.jpg"

paginate = 2
canonifyurls = true
disableSitemap = true
disableRSS = true
disable404 = true
disableHugoGeneratorInject = true
disableKinds = ["events", "page", "home", "section", "taxonomy", "taxonomyTerm", "RSS", "sitemap", "robotsTXT", "404"]
paginatePath = "events/page"

[params.settings]
    events = true
    notice = true
